In [5]:
import pandas as pd

In [6]:
year_by_total_ott_genre=pd.read_csv('2021-2025_total_ott_genre.csv', encoding='cp949')
year_by_total_ott_genre

,구분별(1),구분별(2),시점,응답자수 (명),영화 (%),예능/오락(개인방송 콘텐츠 포함) (%),드라마 (%),교양/다큐멘터리 (%),교육/학습 (%),애니메이션(만화) (%),스포츠 (%),뉴스 (%),공연(콘서트 연극 뮤지컬 등) (%),기타 (%)
0,전체,소계,2021,8293.7,9.0,44.5,20.6,3.8,2.4,3.1,6.7,8.7,-,1.1
1,성별,남,2021,4283.5,11.2,44.6,10.8,3.9,2.2,2.9,12.1,11.4,-,1.0
2,성별,여,2021,4010.2,6.7,44.5,31.1,3.7,2.6,3.3,1.0,5.8,-,1.2
3,연령,만10대미만,2021,174.5,0.4,40.8,0.4,0.6,8.7,47.8,0.3,0.9,-,0.0
4,연령,만10-19세,2021,880.1,4.0,59.1,7.7,3.3,9.5,13.2,2.0,0.6,-,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420,가구주와의관계,부모(배우자부모포함),2025,56.8,0.3,67.6,17.4,0.7,0.0,0.0,13.0,1.0,0.0,0.0
421,가구주와의관계,조부모(배우자조부모포함),2025,1.3,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
422,가구주와의관계,형제자매/그배우자,2025,85.4,0.9,75.0,21.9,0.0,0.8,1.3,0.0,0.0,0.0,0.0
423,가구주와의관계,기타친인척,2025,15.1,0.0,97.3,2.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0
424,가구주와의관계,동거인,2025,16.8,0.0,89.8,0.0,0.0,0.0,0.0,10.2,0.0,0.0,0.0

In [7]:
year_by_df_ott_genre=pd.read_csv('2021-2025_df_ott_genre.csv', encoding='cp949')
# '시점', '구분별(1)', '구분별(2)' 컬럼을 기준으로 데이터를 그룹화합니다.
year_and_age_grouped_data = year_by_df_ott_genre.groupby(['시점', '구분별(1)', '구분별(2)']).sum(numeric_only=True)
display(year_and_age_grouped_data)

                     응답자수 (명)  영화 (%)  예능/오락(개인방송 콘텐츠 포함) (%)  드라마 (%)  \
시점   구분별(1) 구분별(2)
2021 연령     만10-19세     880.1     4.0                    59.1      7.7
            만10대미만      174.5     0.4                    40.8      0.4
            만20-29세    1381.4    11.7                    54.6     23.0
            만30-39세    1390.1    12.4                    41.8     23.3
            만40-49세    1585.9    13.8                    40.3     24.2
            만50-59세    1580.6     7.9                    38.5     23.2
            만60-69세    1025.7     3.4                    39.7     20.4
     전체     소계         8293.7     9.0                    44.5     20.6
2022 연령     만10-19세     874.5     5.0                    62.7      6.1
            만10대미만      130.7     0.0                    53.4      0.0
            만20-29세    1321.5    10.9                    56.7     21.6
            만30-39세    1339.3    12.3                    49.6     24.2
            만40-49세    1589.2     9.8                    43.9     24.1
            만50-59세    1648.3     6.7                    49.0     16.8
            만60-69세    1197.2     3.2                    52.8     11.9
     전체     소계         8486.8     7.8                    51.5     17.7
2023 연령     만10-19세     964.5     2.9                    68.8      6.2
            만10대미만      123.7     0.0                    31.8      1.3
            만20-29세    1168.4     7.8                    59.1     20.4
            만30-39세    1318.7     9.9                    52.4     22.8
            만40-49세    1578.4    13.9                    39.6     22.9
            만50-59세    1653.5     8.4                    46.9     15.9
            만60-69세    1317.0     3.2                    49.9     13.3
     전체     소계         8594.8     7.6                    50.8     16.8
2024 연령     만10-19세     856.6     7.8                    66.9      6.6
            만10대미만       82.4     0.0                    46.2      0.0
            만20-29세     999.3    11.1                    65.6     14.5
            만30-39세    1195.6    15.6                    50.4     20.0
            만40-49세    1381.6    16.9                    48.0     22.3
            만50-59세    1486.0     8.9                    49.4     21.1
            만60-69세    1226.1     4.1                    56.6     13.9
     전체     소계         7755.8    10.3                    54.8     16.7
2025 연령     만10-19세     754.3     4.6                    72.4      5.4
            만10대미만       73.5     0.0                    57.1      0.0
            만20-29세     979.8    11.1                    69.3      9.5
            만30-39세    1172.5    15.1                    62.0     17.0
            만40-49세    1346.7    12.3                    56.2     22.4
            만50-59세    1480.5    10.4                    56.2     17.0
            만60-69세    1277.7     4.2                    58.9     16.9
     전체     소계         7648.1     9.3                    61.5     15.4

                     교양/다큐멘터리 (%)  교육/학습 (%)  애니메이션(만화) (%)  스포츠 (%)  뉴스 (%)  \
시점   구분별(1) 구분별(2)
2021 연령     만10-19세           3.3        9.5           13.2      2.0     0.6
            만10대미만            0.6        8.7           47.8      0.3     0.9
            만20-29세           2.2        2.4            0.8      3.9     1.2
            만30-39세           4.5        0.8            2.2      8.7     5.2
            만40-49세           3.9        1.2            0.4      7.5     7.6
            만50-59세           3.9        1.8            0.2     10.3    12.8
            만60-69세           5.2        0.5            0.2      7.5    20.7
     전체     소계                3.8        2.4            3.1      6.7     8.7
2022 연령     만10-19세           0.4        5.2           16.4      2.0     0.6
            만10대미만            0.0       18.4           28.2      0.0     0.0
            만20-29세           1.7        1.1            0.8      4.8     1.1
            만30-39세           1.5        1.5            1.1      5.7     3.5
            만40-49세           2.7        1.3            0.9      7.2     8.7
            만50-59세           5.1        1.5            0.2      6.9    11.9
            만60-69세           5.3        0.7            0.1      8.0    15.2
     전체     소계                3.2        1.9            2.6      5.8     7.7
2023 연령     만10-19세           0.3        2.7           13.8      2.5     0.6
            만10대미만            0.0       15.5           44.0      4.1     0.0
            만20-29세           1.4        1.3            1.7      3.3     1.3
            만30-39세           2.7        1.3            0.4      4.4     2.7
            만40-49세           4.1        1.0            1.3      5.9     6.2
            만50-59세           5.0        1.4            0.1      7.4     9.1
            만60-69세           6.6        1.1            0.0      6.4    13.3
     전체     소계                4.0        1.6            2.8      5.1     6.4
2024 연령     만10-19세           0.0        3.4           10.5      2.0     1.0
            만10대미만            0.0       10.6           32.7     10.6     0.0
            만20-29세           0.7        0.7            1.3      3.2     1.0
            만30-39세           1.3        0.3            0.5      8.0     2.6
            만40-49세           1.6        0.5            0.1      5.6     4.2
            만50-59세           3.1        0.8            0.1      7.8     6.9
            만60-69세           6.2        0.6            0.0      5.9     7.1
     전체     소계                2.6        1.0            1.8      5.6     4.7
2025 연령     만10-19세           0.9        3.9            5.8      5.1     0.4
            만10대미만            0.0        0.0           31.1     11.8     0.0
            만20-29세           0.4        0.7            2.0      5.5     0.7
            만30-39세           0.8        0.2            0.6      2.7     0.9
            만40-49세           1.4        0.4            0.7      3.3     2.1
            만50-59세           2.6        0.4            0.1      6.0     6.0
            만60-69세           3.8        0.2            0.0      4.0     8.5
     전체     소계                1.9        0.7            1.4      4.4     3.9

                     기타 (%)
시점   구분별(1) 구분별(2)
2021 연령     만10-19세     0.5
            만10대미만      0.0
            만20-29세     0.2
            만30-39세     1.0
            만40-49세     1.1
            만50-59세     1.3
            만60-69세     2.4
     전체     소계          1.1
2022 연령     만10-19세     0.0
            만10대미만      0.0
            만20-29세     0.0
            만30-39세     0.0
            만40-49세     0.1
            만50-59세     0.1
            만60-69세     0.0
     전체     소계          0.1
2023 연령     만10-19세     0.0
            만10대미만      0.0
            만20-29세     0.1
            만30-39세     0.1
            만40-49세     0.1
            만50-59세     0.2
            만60-69세     0.5
     전체     소계          0.2
2024 연령     만10-19세     0.0
            만10대미만      0.0
            만20-29세     0.0
            만30-39세     0.0
            만40-49세     0.0
            만50-59세     0.0
            만60-69세     0.7
     전체     소계          0.2
2025 연령     만10-19세     0.4
            만10대미만      0.0
            만20-29세     0.2
            만30-39세     0.0
            만40-49세     0.0
            만50-59세     0.0
            만60-69세     0.0
     전체     소계          0.1

In [8]:
import pandas as pd
import numpy as np

# Make a copy to avoid modifying the original dataframe
year_by_total_ott_genre_cleaned = year_by_total_ott_genre.copy()

# Convert columns with '-' to numeric, treating '-' as NaN
for col in ['영화 (%)', '예능/오락(개인방송 콘텐츠 포함) (%)', '드라마 (%)', '교양/다큐멘터리 (%)',
            '교육/학습 (%)', '애니메이션(만화) (%)', '스포츠 (%)', '뉴스 (%)',
            '공연(콘서트 연극 뮤지컬 등) (%)', '기타 (%)']:
    if col in year_by_total_ott_genre_cleaned.columns:
        # Replace '-' with NaN, then convert to numeric
        year_by_total_ott_genre_cleaned[col] = year_by_total_ott_genre_cleaned[col].replace('-', np.nan).astype(float)

# Reset index of year_and_age_grouped_data for merging
year_and_age_grouped_data_reset = year_and_age_grouped_data.reset_index()

# Identifier columns for merging
id_columns = ['시점', '구분별(1)', '구분별(2)']

# Identify common numeric columns for comparison (excluding id_columns)
# Filter for columns that are numeric in both dataframes (after cleaning)
common_numeric_cols_total = year_by_total_ott_genre_cleaned.select_dtypes(include=np.number).columns.drop('시점', errors='ignore')
common_numeric_cols_grouped = year_and_age_grouped_data_reset.select_dtypes(include=np.number).columns.drop('시점', errors='ignore')

comparison_columns = list(set(common_numeric_cols_total) & set(common_numeric_cols_grouped))

# Perform an outer merge to capture all possible rows from both dataframes
merged_for_comparison = pd.merge(
    year_by_total_ott_genre_cleaned,
    year_and_age_grouped_data_reset,
    on=id_columns,
    how='outer',
    suffixes=('_total', '_grouped')
)

# Initialize a dictionary to store discrepancies
discrepancies = {}

# Iterate through each common numeric column to find differences
for col in comparison_columns:
    col_total = f"{col}_total"
    col_grouped = f"{col}_grouped"

    # Check for three types of discrepancies:
    # 1. Values exist in both but are not close (for floats)
    # 2. Value exists in '_total' but is NaN in '_grouped' (missing in grouped data)
    # 3. Value exists in '_grouped' but is NaN in '_total' (missing in total data)

    # Mask for case 1: both non-NaN and numerically different
    mask_diff_values = (
        merged_for_comparison[col_total].notna() &
        merged_for_comparison[col_grouped].notna() &
        ~np.isclose(merged_for_comparison[col_total], merged_for_comparison[col_grouped], rtol=1e-05, atol=1e-08, equal_nan=False)
    )

    # Mask for case 2: missing in _grouped (value in _total, NaN in _grouped)
    mask_missing_grouped = (
        merged_for_comparison[col_total].notna() &
        merged_for_comparison[col_grouped].isna()
    )

    # Mask for case 3: missing in _total (NaN in _total, value in _grouped)
    mask_missing_total = (
        merged_for_comparison[col_total].isna() &
        merged_for_comparison[col_grouped].notna()
    )

    # Combine all discrepancy masks
    total_discrepancy_mask = mask_diff_values | mask_missing_grouped | mask_missing_total

    if total_discrepancy_mask.any():
        discrepancies[col] = merged_for_comparison[total_discrepancy_mask][id_columns + [col_total, col_grouped]]

# Display results
if discrepancies:
    print("`year_by_total_ott_genre`와 `year_and_age_grouped_data` 변수 간의 교차 검증 결과, 다음과 같은 불일치가 발견되었습니다:\n")
    for col, diff_df in discrepancies.items():
        print(f"컬럼: '{col}'에서 불일치\n")
        display(diff_df)
        print("\n" + "="*80 + "\n")
else:
    print("`year_by_total_ott_genre`와 `year_and_age_grouped_data` 변수 간의 공통 숫자 컬럼에서 중요한 불일치가 발견되지 않았습니다.")

`year_by_total_ott_genre`와 `year_and_age_grouped_data` 변수 간의 교차 검증 결과, 다음과 같은 불일치가 발견되었습니다:

컬럼: '드라마 (%)'에서 불일치

       시점   구분별(1)   구분별(2)  드라마 (%)_total  드라마 (%)_grouped
0    2021    가구원수1     1인가구           30.0              NaN
1    2021    가구원수1     2인가구           19.3              NaN
2    2021    가구원수1   3인이상가구           19.5              NaN
3    2021  가구주와의관계      가구주           16.7              NaN
4    2021  가구주와의관계  가구주의배우자           37.1              NaN
..    ...      ...      ...            ...              ...
420  2025      학력1     대졸이하           17.3              NaN
421  2025      학력1  대학원재학이상           20.1              NaN
422  2025      학력1      미취학            0.0              NaN
423  2025      학력1     중졸이하           11.7              NaN
424  2025      학력1     초졸이하            2.7              NaN

[385 rows x 5 columns]

================================================================================

컬럼: '스포츠 (%)'에서 불일치

       시점   구분별(1)   구분별(2)  스포츠 (%)_total  스포츠 (%)_grouped
0    2021    가구원수1     1인가구            6.0              NaN
1    2021    가구원수1     2인가구            5.6              NaN
2    2021    가구원수1   3인이상가구            7.3              NaN
3    2021  가구주와의관계      가구주           11.8              NaN
4    2021  가구주와의관계  가구주의배우자            1.7              NaN
..    ...      ...      ...            ...              ...
420  2025      학력1     대졸이하            4.3              NaN
421  2025      학력1  대학원재학이상            2.9              NaN
422  2025      학력1      미취학            0.0              NaN
423  2025      학력1     중졸이하            2.8              NaN
424  2025      학력1     초졸이하            6.1              NaN

[385 rows x 5 columns]

================================================================================

컬럼: '교육/학습 (%)'에서 불일치

       시점   구분별(1)   구분별(2)  교육/학습 (%)_total  교육/학습 (%)_grouped
0    2021    가구원수1     1인가구              0.0                NaN
1    2021    가구원수1     2인가구              0.5                NaN
2    2021    가구원수1   3인이상가구              3.5                NaN
3    2021  가구주와의관계      가구주              0.7                NaN
4    2021  가구주와의관계  가구주의배우자              2.2                NaN
..    ...      ...      ...              ...                ...
420  2025      학력1     대졸이하              0.5                NaN
421  2025      학력1  대학원재학이상              3.1                NaN
422  2025      학력1      미취학              0.0                NaN
423  2025      학력1     중졸이하              2.6                NaN
424  2025      학력1     초졸이하              1.0                NaN

[385 rows x 5 columns]

================================================================================

컬럼: '영화 (%)'에서 불일치

       시점   구분별(1)   구분별(2)  영화 (%)_total  영화 (%)_grouped
0    2021    가구원수1     1인가구          11.3             NaN
1    2021    가구원수1     2인가구           9.7             NaN
2    2021    가구원수1   3인이상가구           8.4             NaN
3    2021  가구주와의관계      가구주           9.9             NaN
4    2021  가구주와의관계  가구주의배우자           5.4             NaN
..    ...      ...      ...           ...             ...
420  2025      학력1     대졸이하          12.3             NaN
421  2025      학력1  대학원재학이상          10.4             NaN
422  2025      학력1      미취학           0.0             NaN
423  2025      학력1     중졸이하           2.8             NaN
424  2025      학력1     초졸이하           2.3             NaN

[385 rows x 5 columns]

================================================================================

컬럼: '교양/다큐멘터리 (%)'에서 불일치

       시점   구분별(1)   구분별(2)  교양/다큐멘터리 (%)_total  교양/다큐멘터리 (%)_grouped
0    2021    가구원수1     1인가구                 2.0                   NaN
1    2021    가구원수1     2인가구                 4.4                   NaN
2    2021    가구원수1   3인이상가구                 3.9                   NaN
3    2021  가구주와의관계      가구주                 4.2                   NaN
4    2021  가구주와의관계  가구주의배우자                 4.9                   NaN
..    ...      ...      ...                 ...                   ...
420  2025      학력1     대졸이하                 1.3                   NaN
421  2025      학력1  대학원재학이상                 5.4                   NaN
422  2025      학력1      미취학                 0.0                   NaN
423  2025      학력1     중졸이하                 3.2                   NaN
424  2025      학력1     초졸이하                 1.4                   NaN

[385 rows x 5 columns]

================================================================================

컬럼: '예능/오락(개인방송 콘텐츠 포함) (%)'에서 불일치

,시점,구분별(1),구분별(2),예능/오락(개인방송 콘텐츠 포함) (%)_total,예능/오락(개인방송 콘텐츠 포함) (%)_grouped
0,2021,가구원수1,1인가구,42.2,NaN
1,2021,가구원수1,2인가구,45.7,NaN
2,2021,가구원수1,3인이상가구,44.5,NaN
3,2021,가구주와의관계,가구주,40.3,NaN
4,2021,가구주와의관계,가구주의배우자,38.4,NaN
...,...,...,...,...,...
420,2025,학력1,대졸이하,59.3,NaN
421,2025,학력1,대학원재학이상,54.2,NaN
422,2025,학력1,미취학,0.0,NaN
423,2025,학력1,중졸이하,66.6,NaN
424,2025,학력1,초졸이하,72.2,NaN

================================================================================

컬럼: '뉴스 (%)'에서 불일치

       시점   구분별(1)   구분별(2)  뉴스 (%)_total  뉴스 (%)_grouped
0    2021    가구원수1     1인가구           7.8             NaN
1    2021    가구원수1     2인가구          12.5             NaN
2    2021    가구원수1   3인이상가구           7.5             NaN
3    2021  가구주와의관계      가구주          14.6             NaN
4    2021  가구주와의관계  가구주의배우자           7.3             NaN
..    ...      ...      ...           ...             ...
420  2025      학력1     대졸이하           3.3             NaN
421  2025      학력1  대학원재학이상           0.4             NaN
422  2025      학력1      미취학           0.0             NaN
423  2025      학력1     중졸이하           5.4             NaN
424  2025      학력1     초졸이하           3.4             NaN

[385 rows x 5 columns]

================================================================================

컬럼: '애니메이션(만화) (%)'에서 불일치

       시점   구분별(1)   구분별(2)  애니메이션(만화) (%)_total  애니메이션(만화) (%)_grouped
0    2021    가구원수1     1인가구                  0.0                    NaN
1    2021    가구원수1     2인가구                  0.3                    NaN
2    2021    가구원수1   3인이상가구                  4.6                    NaN
3    2021  가구주와의관계      가구주                  0.7                    NaN
4    2021  가구주와의관계  가구주의배우자                  0.9                    NaN
..    ...      ...      ...                  ...                    ...
420  2025      학력1     대졸이하                  0.8                    NaN
421  2025      학력1  대학원재학이상                  3.1                    NaN
422  2025      학력1      미취학                100.0                    NaN
423  2025      학력1     중졸이하                  2.9                    NaN
424  2025      학력1     초졸이하                  5.8                    NaN

[385 rows x 5 columns]

================================================================================

컬럼: '기타 (%)'에서 불일치

       시점   구분별(1)   구분별(2)  기타 (%)_total  기타 (%)_grouped
0    2021    가구원수1     1인가구           0.7             NaN
1    2021    가구원수1     2인가구           2.0             NaN
2    2021    가구원수1   3인이상가구           0.9             NaN
3    2021  가구주와의관계      가구주           1.1             NaN
4    2021  가구주와의관계  가구주의배우자           2.2             NaN
..    ...      ...      ...           ...             ...
420  2025      학력1     대졸이하           0.0             NaN
421  2025      학력1  대학원재학이상           0.0             NaN
422  2025      학력1      미취학           0.0             NaN
423  2025      학력1     중졸이하           0.5             NaN
424  2025      학력1     초졸이하           0.6             NaN

[385 rows x 5 columns]

================================================================================

컬럼: '응답자수 (명)'에서 불일치

       시점   구분별(1)   구분별(2)  응답자수 (명)_total  응답자수 (명)_grouped
0    2021    가구원수1     1인가구           951.3               NaN
1    2021    가구원수1     2인가구          1947.3               NaN
2    2021    가구원수1   3인이상가구          5395.1               NaN
3    2021  가구주와의관계      가구주          3544.6               NaN
4    2021  가구주와의관계  가구주의배우자          1981.7               NaN
..    ...      ...      ...             ...               ...
420  2025      학력1     대졸이하          3867.5               NaN
421  2025      학력1  대학원재학이상           114.5               NaN
422  2025      학력1      미취학             8.7               NaN
423  2025      학력1     중졸이하           631.6               NaN
424  2025      학력1     초졸이하           443.3               NaN

[385 rows x 5 columns]

================================================================================